<?php

namespace App\Classes;

use App\Models\Lang;
use App\Models\Translation;
use Nwidart\Modules\Facades\Module;

class LangTrans
{
    public static $mainTranslations = [
        'common' => [
            'enabled' => 'Habilitado',
            'disabled' => 'Deshabilitado',
            'id' => 'Id',
            'action' => 'Acción',
            'placeholder_default_text' => 'Por favor, introduzca {0}',
            'placeholder_social_text' => 'Por favor, introduzca la URL de {0}',
            'placeholder_search_text' => 'Buscar por {0}',
            'select_default_text' => 'Seleccionar {0}...',
            'create' => 'Crear',
            'edit' => 'Editar',
            'update' => 'Actualizar',
            'cancel' => 'Cancelar',
            'delete' => 'Eliminar',
            'success' => 'Éxito',
            'error' => 'Error',
            'yes' => 'Sí',
            'no' => 'No',
            'fix_errors' => 'Por favor, corrija los errores a continuación.',
            'cancelled' => 'Cancelado',
            'pending' => 'Pendiente',
            'paid' => 'Pagado',
            'canceled' => 'Cancelado',
            'completed' => 'Completado',
            'rejected' => 'Rechazado',
            'save' => 'Guardar',
            'all' => 'Todos',
            'name' => 'Nombre',
            'back' => 'Atrás',
            'max_amount' => 'Cantidad Máx.',
            'date_time' => 'Fecha y hora',
            'select_time' => 'Seleccionar hora',
            'start_date' => 'Fecha de inicio',
            'end_date' => 'Fecha de finalización',
            'search' => 'Buscar',
            'date' => 'Fecha',
            'confirm' => 'Confirmar',
            'title' => 'Título',
            'value' => 'Valor',
            'add' => 'Agregar',
            'view' => 'Ver',
            'download' => 'Descargar',
            'total' => 'Total',
            'email' => 'Correo electrónico',
            'phone' => 'Teléfono',
            'purchase_code' => 'Código de compra',
            'verify_purchase' => 'Verificar compra',
            'install' => 'Instalar',
            'installing' => 'Instalando',
            'updating' => 'Actualizando',
            'free' => 'Gratis',
            'domain' => 'Dominio',
            'verify' => 'Verificar',
            'send' => 'Enviar',
            'upload' => 'Subir',
            'view_all' => 'Ver todo',
            'unpaid' => 'No pagado',
            'loading' => 'Cargando',
            'update_app' => 'Actualizar aplicación',
            'welcome_back' => 'Bienvenido {0}',
            'off' => 'Apagado',
            'on_create' => 'Al crear',
            'on_update' => 'Al actualizar',
            'on_delete' => 'Al eliminar',
            'demo_account_credentials' => 'Credenciales de inicio de sesión de la cuenta de demostración',
            'created_by' => 'Creado por',
            'import' => 'Importar',
            'file' => 'Archivo',
            'copy_url' => 'Copiar URL',
            'print' => 'Imprimir',
            'amount' => 'Cantidad',
            'status' => 'Estado',
            'active' => 'Activo',
            'inactive' => 'Inactivo',
            'verified' => 'Verificado',
            'configure' => 'Configurar',
            'logo' => 'Logotipo',
            'slug' => 'Slug',
            'description' => 'Descripción',
            'image' => 'Imagen',
            'not_allowed' => 'No permitido',
            'details' => 'Detalles',
            'text' => 'Texto',
            'link' => 'Enlace',
            'start' => 'Comenzar',
            'stop' => 'Detener',
            'are_you_sure' => '¿Está seguro?',
            'basic_details' => 'Detalles básicos',
            'more' => 'Más',
            'other' => 'Otro',
            'continue' => 'Continuar',
            'docs' => 'Documentos',
            'e_sign' => 'Signeasy',
            'created_at' => 'Creado en',
            'updated_at' => 'Actualizado en',
            'close' => 'Cerrar',
            'template_id' => 'ID de plantilla',
            'include' => 'Incluir',
            'today' => 'Hoy',
            'general' => 'General',
            'unknown' => 'Desconocido',
            'export' => 'Exportar',
            'columns' => 'Columnas',
            'date_range' => 'Rango de fechas',
            'include_all_as_default' => '(Incluir todo por defecto)',
            'export_table' => 'Exportar {0}',
            'export_as' => 'Exportar como',
            'address' => 'Dirección',
        ],
        'menu' => [
            'dashboard' => 'Tablero',
            'users' => 'Usuarios',
            'staff_members' => 'Miembros del personal',
            'settings' => 'Configuraciones',
            'company' => 'Configuración de la empresa',
            'profile' => 'Perfil',
            'translations' => 'Traducciones',
            'languages' => 'Idiomas',
            'roles' => 'Roles y permisos',
            'currencies' => 'Monedas',
            'login' => 'Iniciar sesión',
            'logout' => 'Cerrar sesión',
            'storage_settings' => 'Configuración de almacenamiento',
            'email_settings' => 'Configuración de correo electrónico',
            'database_backup' => 'Copia de seguridad de la base de datos',
            'companies' => 'Empresas',
            'email_templates' => 'Plantillas de correo electrónico',
            'forms'  => 'Formularios',
            'user_management' => 'Administración de usuarios',
            'messaging' => 'Mensajería',
            'setup_company' => 'Configurar empresa',
            'form_field_names' => 'Campos de la tabla de clientes potenciales',
            'templates' => 'Plantillas',
            'categories' => 'Categorías',
            'suppliers' => 'Proveedores',
            'products' => 'Inventario',
            'clients' => 'Clientes',
            'orders' => 'Pedidos',
        ],
        'dashboard' => [
            'dashboard' => 'Tablero',
            'recent_orders' => 'Pedidos recientes',
            'order_id' => 'ID del pedido',
            'client' => 'Cliente',
            'amount' => 'Cantidad',
            'date' => 'Fecha',
            'total_orders' => 'Total de pedidos',
            'total_revenue' => 'Ingresos totales',
            'total_clients' => 'Total de clientes',
            'total_products' => 'Total de productos',
            'sales_chart' => 'Gráfico de ventas',
            'stock_alert' => 'Alerta de stock',
        ],
        'user' => [
            'staff_members' => 'Miembros del personal',
            'add' => 'Agregar nuevo miembro del personal',
            'edit' => 'Editar miembro del personal',
            'created' => 'Miembro del personal creado con éxito',
            'updated' => 'Miembro del personal actualizado con éxito',
            'deleted' => 'Miembro del personal eliminado con éxito',
            'staff_member_details' => 'Detalles del miembro del personal',
            'staff_member' => 'Miembro del personal',
            'delete_message' => '¿Está seguro de que desea eliminar este miembro del personal?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar el miembro del personal seleccionado?',
            'import_staff_members' => 'Importar miembros del personal',
            'email_phone' => 'Correo electrónico o teléfono',
            'user' => 'Usuario',
            'name' => 'Nombre',
            'created_at' => 'Creado en',
            'email' => 'Correo electrónico',
            'password' => 'Contraseña',
            'login_enabled' => 'Inicio de sesión habilitado',
            'profile_image' => 'Imagen de perfil',
            'company_name' => 'Nombre de la empresa',
            'phone' => 'Número de teléfono',
            'address' => 'Dirección',
            'city' => 'Ciudad',
            'state' => 'Estado',
            'country' => 'País',
            'zipcode' => 'Código postal',
            'status' => 'Estado',
            'role' => 'Rol',
            'profile_updated' => 'Perfil actualizado con éxito',
            'password_blank' => 'Deje en blanco si no desea actualizar la contraseña.',
            'admin_account_details' => 'Detalles de la cuenta de administrador',
            'import_users' => 'Importar usuarios',
            'staff_members_details' => 'Detalles de los miembros del personal',
            'export_users' => 'Exportar usuarios',
            'time_taken' => 'Tiempo tomado',
            'count_assigned_sales' => 'Contar ventas asignadas',
            'count_sent_sms_messages' => 'Contar mensajes SMS enviados',
            'roles' => 'Roles',
        ],
        'role' => [
            'add' => 'Agregar nuevo rol',
            'edit' => 'Editar rol',
            'created' => 'Rol creado con éxito',
            'updated' => 'Rol actualizado con éxito',
            'deleted' => 'Rol eliminado con éxito',
            'role_details' => 'Detalles del rol',
            'delete_message' => '¿Está seguro de que desea eliminar este rol?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar el rol seleccionado?',
            'display_name' => 'Nombre para mostrar',
            'role_name' => 'Nombre del rol',
            'description' => 'Descripción',
            'user_management' => 'Administración de usuarios',
            'permissions' => 'Permisos',
        ],
        'email_template' => [
            'add' => 'Agregar nueva plantilla de correo electrónico',
            'edit' => 'Editar plantilla de correo electrónico',
            'created' => 'Plantilla de correo electrónico creada con éxito',
            'updated' => 'Plantilla de correo electrónico actualizada con éxito',
            'deleted' => 'Plantilla de correo electrónico eliminada con éxito',
            'email_template_details' => 'Detalles de la plantilla de correo electrónico',
            'delete_message' => '¿Está seguro de que desea eliminar esta plantilla de correo electrónico?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar la plantilla de correo electrónico seleccionada?',
            'name' => 'Nombre',
            'subject' => 'Asunto',
            'body' => 'Cuerpo',
            'message' => 'Mensaje',
            'status' => 'Estado',
            'sharable' => 'Compartible',
            'sharable_message' => '¿Es esta plantilla compartible con otros miembros del equipo?',
            'status_update' => 'Estado actualizado con éxito',
            'mail_send_successfully' => 'Correo electrónico enviado con éxito',
            'mail_send_error_message' => 'Póngase en contacto con el administrador para configurar la configuración de correo',
            'additionals' => 'Adicionales',
        ],
        'staff_member' => [
            'add' => 'Agregar nuevo miembro del personal',
            'edit' => 'Editar miembro del personal',
            'created' => 'Miembro del personal creado con éxito',
            'updated' => 'Miembro del personal actualizado con éxito',
            'deleted' => 'Miembro del personal eliminado con éxito',
            'staff_member_details' => 'Detalles del miembro del personal',
            'staff_member' => 'Miembro del personal',
            'delete_message' => '¿Está seguro de que desea eliminar este miembro del personal?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar el miembro del personal seleccionado?',
            'import_staff_members' => 'Importar miembros del personal',
        ],
        'form' => [
            'add' => 'Agregar nuevo formulario',
            'edit' => 'Editar formulario',
            'created' => 'Formulario creado con éxito',
            'updated' => 'Formulario actualizado con éxito',
            'deleted' => 'Formulario eliminado con éxito',
            'form_details' => 'Detalles del formulario',
            'delete_message' => '¿Está seguro de que desea eliminar este formulario?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar el formulario seleccionado?',
            'form' => 'Formulario',
            'name' => 'Nombre',
            'status' => 'Estado',
            'form_fields' => 'Campos del formulario',
            'add_form_field' => 'Agregar campo de formulario',
            'field_name' => 'Nombre del campo',
            'status_update' => 'Estado actualizado con éxito',
        ],
        'form_field_name' => [
            'add' => 'Agregar nuevo campo de tabla de clientes potenciales',
            'edit' => 'Editar campo de tabla de clientes potenciales',
            'created' => 'Campo de tabla de clientes potenciales creado con éxito',
            'updated' => 'Campo de tabla de clientes potenciales actualizado con éxito',
            'deleted' => 'Campo de tabla de clientes potenciales eliminado con éxito',
            'form_field_name_details' => 'Detalles del campo de tabla de clientes potenciales',
            'delete_message' => '¿Está seguro de que desea eliminar este nombre de campo de formulario?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar el nombre de campo de formulario seleccionado?',
            'field_name' => 'Nombre del campo',
            'similar_field_names' => 'Nombres de campo similares',
            'visible' => 'Visible',
            'add_field' => 'Agregar campo',
            'status_update' => 'Estado actualizado con éxito',
        ],
        'company' => [
            'add' => 'Agregar nueva empresa',
            'edit' => 'Editar empresa',
            'created' => 'Empresa creada con éxito',
            'updated' => 'Empresa actualizada con éxito',
            'deleted' => 'Empresa eliminada con éxito',
            'currency_details' => 'Detalles de la empresa',
            'delete_message' => '¿Está seguro de que desea eliminar esta empresa?',
            'name' => 'Nombre de la empresa',
            'short_name' => 'Nombre corto de la empresa',
            'email' => 'Correo electrónico de la empresa',
            'phone' => 'Teléfono de la empresa',
            'address' => 'Dirección de la empresa',
            'currency' => 'Moneda',
            'logo' => 'Logotipo de la empresa',
            'left_sidebar_theme' => 'Tema de la barra lateral izquierda',
            'dark' => 'Oscuro',
            'light' => 'Claro',
            'dark_logo' => 'Logotipo oscuro',
            'light_logo' => 'Logotipo claro',
            'small_dark_logo' => 'Logotipo oscuro pequeño',
            'small_light_logo' => 'Logotipo claro pequeño',
            'primary_color' => 'Color primario',
            'default_timezone' => 'Zona horaria predeterminada',
            'date_format' => 'Formato de fecha',
            'time_format' => 'Formato de hora',
            'auto_detect_timezone' => 'Detectar automáticamente la zona horaria',
            'app_debug' => 'Depuración de la aplicación',
            'login_image' => 'Imagen de inicio de sesión',
            'layout' => 'Diseño',
            'rtl' => 'RTL',
            'ltr' => 'LTR',
            'shortcut_menu_Placement' => 'Agregar ubicación del menú',
            'top_and_bottom' => 'Arriba y abajo',
            'top_header' => 'Encabezado superior',
            'bottom_corner' => 'Esquina inferior',
            'shortcut_menu_setting' => 'Agregar configuración del menú',
            'menu_setting_updated' => 'Configuración del menú actualizada',
            'basic_details' => 'Detalles básicos',
            'details' => 'Detalles',
            'register_date' => 'Fecha de registro',
            'total_users' => 'Total de usuarios',
            'update_app_notification' => 'Actualizar notificación de la aplicación',
            'language' => 'Idioma'
        ],
        'currency' => [
            'add' => 'Agregar nueva moneda',
            'edit' => 'Editar moneda',
            'created' => 'Moneda creada con éxito',
            'updated' => 'Moneda actualizada con éxito',
            'deleted' => 'Moneda eliminada con éxito',
            'currency_details' => 'Detalles de la moneda',
            'delete_message' => '¿Está seguro de que desea eliminar esta moneda?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar la moneda seleccionada?',
            'name' => 'Nombre de la moneda',
            'symbol' => 'Símbolo de la moneda',
            'position' => 'Posición de la moneda',
            'front' => 'Delante',
            'front_position_example' => 'Ejemplo: $100',
            'behind' => 'Detrás',
            'behind_position_example' => 'Ejemplo: 100$',
            'code' => 'Código de moneda',
        ],
        'langs' => [
            'add' => 'Agregar nuevo idioma',
            'edit' => 'Editar idioma',
            'details' => 'Detalles del idioma',
            'created' => 'Idioma creado con éxito',
            'updated' => 'Idioma actualizado con éxito',
            'deleted' => 'Idioma eliminado con éxito',
            'delete_message' => '¿Está seguro de que desea eliminar este idioma?',
            'view_all_langs' => 'Ver todos los idiomas',
            'status_updated' => 'Estado del idioma actualizado',
            'name' => 'Nombre',
            'key' => 'Clave',
            'flag' => 'Bandera',
            'enabled' => 'Habilitado',
        ],
        'translations' => [
            'fetch_new_translations' => 'Obtener nuevas traducciones',
            'reload_translations' => 'Recargar traducciones',
            'reload_successfully' => 'Traducciones recargadas con éxito',
            'fetched_successfully' => 'Traducciones obtenidas con éxito',
            'import_translations' => 'Importar traducciones',
        ],
        'storage_settings' => [
            'updated' => 'Configuración de almacenamiento actualizada',
            'storage' => 'Almacenamiento',
            'local' => 'Local',
            'aws' => 'Almacenamiento AWS S3',
            'aws_key' => 'Clave de AWS',
            'aws_secret' => 'Secreto de AWS',
            'aws_region' => 'Región de AWS',
            'aws_bucket' => 'Bucket de AWS',
        ],
        'mail_settings' => [
            'updated' => 'Configuración de correo actualizada',
            'mail_driver' => 'Controlador de correo',
            'none' => 'Ninguno',
            'mail' => 'Correo',
            'smtp' => 'SMTP',
            'from_name' => 'Nombre del remitente',
            'from_email' => 'Correo electrónico del remitente',
            'host' => 'Host',
            'port' => 'Puerto',
            'encryption' => 'Cifrado',
            'username' => 'Nombre de usuario',
            'password' => 'Contraseña',
            'send_test_mail' => 'Enviar correo de prueba',
            'send_mail_setting_saved' => 'Configuración de envío de correo guardada',
            'enable_mail_queue' => 'Habilitar cola de correo',
            'send_mail_for' => 'Enviar correo para',
            'email' => 'Dirección de correo electrónico para la que desea enviar el correo de prueba',
            'test_mail_sent_successfully' => 'Correo de prueba enviado con éxito',
            'notificaiton_will_be_sent_to_company' => 'La notificación se enviará al correo electrónico de la empresa',
        ],
        'database_backup' => [
            'file' => 'Archivo',
            'file_size' => 'Tamaño del archivo',
            'generate_backup' => 'Generar copia de seguridad',
            'delete_backup' => 'Eliminar copia de seguridad',
            'backup_generated_successfully' => 'Copia de seguridad generada con éxito',
            'are_you_sure_generate_backup' => '¿Está seguro de que desea generar una copia de seguridad de la base de datos?',
            'are_you_sure_delete_backup' => '¿Está seguro de que desea eliminar esta copia de seguridad de la base de datos?',
            'backup_locaion_is' => 'Todos los archivos de base de datos generados se almacenarán en la carpeta storage/app/public/backup.',
            'settings' => 'Configuraciones de comando',
            'backup_command_setting' => 'Configuración del comando de copia de seguridad',
            'mysqldump_command_path' => 'Ruta del comando mysqldump',
            'command_updated' => 'Comando actualizado con éxito',
            'window_command_path' => 'Si usa XAMPP, será => C:\xampp\mysql\bin\mysqldump.exe',
            'laragon_command_path' => 'Si usa Laragon, será => C:\laragon\bin\mysql\mysql-5.7.24-winx64\bin\mysqldump.exe',
            'linux_command_path' => 'Si está en ubuntu o mac, ejecute el siguiente comando e ingrese la salida aquí => which mysqldump',
            'put_dump_path_command_on_env_file' => 'Encuentre la ruta de volcado de MySQL a continuación y luego agréguela al DUMP_PATH dentro del archivo .env',
        ],
        'messages' => [
            'somehing_went_wrong' => 'Algo salió mal. Póngase en contacto con el administrador.',
            'verify_success' => 'Verificado con éxito. Redirigiendo a la aplicación...',
            'login_success' => 'Inicio de sesión exitoso. Redirigiendo a la aplicación...',
            'login_success_dashboard' => 'Sesión iniciada con éxito en la aplicación.',
            'click_here_to_find_purchase_code' => 'Haga clic aquí para encontrar su código de compra',
            'verification_successfull' => 'Verificación exitosa',
            'other_domain_linked' => 'Otro dominio vinculado',
            'other_domain_linked_with_purchase_code' => 'Otro dominio ya está vinculado con su código de compra. Ingrese su código de compra para obtener más detalles...',
            'first_verify_module_message' => 'Para habilitar, verifique este módulo',
            'are_you_sure_install_message' => '¿Está seguro de que desea instalar?',
            'downloading_started_message' => 'Descarga iniciada. Por favor, espere...',
            'file_extracting_message' => 'Extrayendo archivo. Por favor, espere...',
            'installation_success' => 'Instalación exitosa. Haga clic aquí para recargar la página...',
            'are_you_sure_update_message' => '¿Está seguro de que desea actualizar? Realice una copia de seguridad antes de actualizar.',
            'stmp_success_message' => 'Su configuración SMTP es correcta.',
            'stmp_error_message' => 'Su configuración SMTP es incorrecta. Actualícela para enviar correos.',
            'uploading_failed' => 'Error al cargar',
            'loading_app_message' => 'Cargando... Por favor, espere',
            'fetching_product_details' => 'Estamos obteniendo los detalles del producto. Por favor, espere...',
            'product_is_upto_date' => 'Está utilizando la última versión de la aplicación.',
            'new_app_version_avaialbe' => 'Nueva versión de la aplicación {0} disponible. Actualice para obtener la última versión.',
            'not_able_to_edit_order' => 'Solo el estado del pedido es editable, otros campos no se pueden editar porque este pedido está vinculado a algunos pagos. Elimine esos pagos e intente nuevamente.',
            'click_here_to_download_sample_file' => 'Haga clic aquí para descargar el archivo CSV de muestra',
            'imported_successfully' => 'Importado con éxito',
            'company_admin_password_message' => 'El administrador iniciará sesión con esta contraseña. (Deje en blanco para mantener la contraseña actual)',
            'email_setting_not_configured' => 'Configuración de correo electrónico no configurada',
            'please_configure_email_settings' => 'Configure su configuración de correo electrónico para enviar correos electrónicos. Haga clic aquí para configurar la configuración de correo electrónico.',
        ],
        'popover' => [
            'auto_detect_timezone' => 'Permitir la detección automática de la zona horaria desde el navegador para el usuario que ha iniciado sesión actualmente.',
            'click_here_to_copy_credentials' => 'Haga clic aquí para copiar las credenciales de {0}',
        ],
        'topbar_add_button' => [
            'add_staff_member' => 'Agregar miembro del personal',
            'add_currency' => 'Agregar moneda',
            'add_language' => 'Agregar idioma',
            'add_role' => 'Agregar rol',
        ],
        'setup_company' => [
            'setup_not_completed' => 'Configuración no completada',
            'setup_not_completed_description' => 'La configuración predeterminada de su empresa no se ha completado. Siga las siguientes configuraciones para completar la configuración básica de su empresa...',
            'currency' => 'Moneda',
            'add_first_currency' => 'Agregar primera moneda',
            'company_settings' => 'Configuración de la empresa',
            'set_company_basic_settings' => 'Configurar la configuración básica de la empresa',
            'previous_step' => 'Paso anterior',
            'next_step' => 'Siguiente paso',
            'basic_settings' => 'Configuración básica',
            'theme_settings' => 'Configuración del tema',
            'logo_settings' => 'Configuración del logotipo',
            'save_finish_setup' => 'Guardar y finalizar la configuración',
            'go_to_dashboard' => 'Ir al tablero',
            'setup_running_message' => 'Por favor, espere... estamos configurando la configuración inicial de la empresa.',
            'setup_complete_message' => 'Configuración completada... Haga clic en el enlace de abajo para ver su aplicación...',
        ],
        'docs' => [
            'title' => 'Título del documento',
            'created_at' => 'Creado en',
            'drag_n_drop' => 'Arrastre y suelte archivos, o explore',
            'delete_message' => '¿Está seguro de que desea eliminar este documento?',
            'deleted' => 'Documento eliminado con éxito',
            'deleted_error' => 'Documento no eliminado. Inténtelo de nuevo',
            'add' => 'Nuevo documento',
            'edit' => 'Editar documento',
            'created' => 'Documento creado con éxito',
            'updated' => 'Documento actualizado con éxito',
            'generated_successfully' => 'Documento generado con éxito',
            'generate_error_message' => 'Documento no generado. Inténtelo de nuevo',
            'esign_successfully' => 'Documento enviado a través de Signeasy con éxito',
            'esign_error_message' => 'Documento no enviado a través de Signeasy. Inténtelo de nuevo',
            'selected_delete_message' => '¿Está seguro de que desea eliminar los documentos seleccionados?',
            'doc_timeline_message' => 'Documento cargado por {0} el {1}',
            'doc_timeline_message_deleted' => 'Documento eliminado por {0} el {1}',
            'generated_doc_timeline_message' => 'Documento generado por {0} el {1}',
            'esign_doc_timeline_message' => 'Documento enviado a través de Signeasy por {0} el {1}',
            'voided_doc_timeline_message' => 'Documento anulado por {0} el {1}',
            'generated' => 'Documentos generados',
            'esign' => 'Documentos de Signeasy',
            'uploaded' => 'Archivos cargados',
            'sent_by' => 'Enviado por',
            'signers' => 'Firmantes',
            'signers_left' => 'Firmantes restantes',
            'sent_at' => 'Enviado el',
            'generate_documents' => 'Generar documentos',
            'send_doc_esign' => 'Enviar documento a través de Signeasy',
            'generate_save_doc' => 'Generar y guardar documento',
            'configuration' => 'Configuración del documento',
            'select_template' => 'Seleccionar plantilla para usar',
            'template' => 'Plantilla',
            'delivery_expiration' => 'Configuración de entrega y vencimiento',
            'send_via' => 'Enviar a través de',
            'expiration_date' => 'Fecha de vencimiento',
            'document_expires_on' => 'El documento vence el',
            'defautl_expiration_in' => 'Vencimiento predeterminado en 30 días',
            'sms_templates' => 'Plantillas de SMS',
            'send_for_signature' => 'Enviar para firma',
            'preview' => 'Vista previa',
            'generate_save' => 'Generar y guardar',
            'assign_doc_signers' => 'Asignar firmantes del documento',
            'enforce_signing_order' => 'Exigir orden de firma',
            'signer_type' => 'Tipo de firmante',
            'signer_name' => 'Nombre',
            'signer_email' => 'Correo electrónico',
            'signer_phone' => 'Teléfono',
            'add_signer' => 'Agregar firmante',
            'void' => 'Anular',
            'voiding_reason' => 'Motivo para anular la solicitud',
            'voiding_description' => 'Una vez anulados, los firmantes ya no podrán acceder a este documento. Recibirán una notificación por correo electrónico, junto con su motivo para anular esta solicitud.',
            'add_your_reason' => 'Agregue su motivo aquí (máximo {0} caracteres)',
            'signature_request_voided' => 'Solicitud de firma anulada',
            'error_voiding_signature_request' => 'Error al anular la solicitud de firma',
            'refresh' => 'Actualizar',
            'signed_document_with_audit_trail' => 'Documento firmado con registro de auditoría',
            'signed_document' => 'Documento firmado',
            'audit_trail' => 'Registro de auditoría',
            'send_reminder' => 'Enviar recordatorio',
            'reminder_sent' => 'Recordatorio enviado con éxito',
            'error_sending_reminder' => 'Error al enviar el recordatorio',
            'waiting' => 'Esperando',
            'signed' => 'Firmado',
            'declined' => 'Rechazado',
            'expired' => 'Vencido',
            'voided' => 'Anulado',
            'reminder_too_many_error' => 'Ya ha enviado los recordatorios, espere {0} horas.',
            'refresh_successfully' => 'Documentos actualizados con éxito',
            'waiting_for_signature' => 'Esperando firma',
            'unknown_date' => 'Fecha desconocida',
            'for' => 'para',
            'by' => 'por',
            'viewed' => 'Visto',
        ],
        'categories' => [
            'add' => 'Agregar nueva categoría',
            'edit' => 'Editar categoría',
            'created' => 'Categoría creada con éxito',
            'updated' => 'Categoría actualizada con éxito',
            'deleted' => 'Categoría eliminada con éxito',
            'delete_message' => '¿Está seguro de que desea eliminar esta categoría?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar las categorías seleccionadas?',
        ],
        'suppliers' => [
            'add' => 'Agregar nuevo proveedor',
            'edit' => 'Editar proveedor',
            'created' => 'Proveedor creado con éxito',
            'updated' => 'Proveedor actualizado con éxito',
            'deleted' => 'Proveedor eliminado con éxito',
            'delete_message' => '¿Está seguro de que desea eliminar este proveedor?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar los proveedores seleccionados?',
            'contact_name' => 'Nombre de contacto',
            'contact_email' => 'Correo electrónico de contacto',
            'contact_phone' => 'Teléfono de contacto',
        ],
        'products' => [
            'add' => 'Agregar nuevo artículo',
            'edit' => 'Editar artículo',
            'created' => 'Artículo creado con éxito',
            'updated' => 'Artículo actualizado con éxito',
            'deleted' => 'Artículo eliminado con éxito',
            'delete_message' => '¿Está seguro de que desea eliminar este artículo?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar los artículos seleccionados?',
            'price' => 'Precio',
            'stock_quantity' => 'Cantidad en stock',
            'initial_stock_quantity' => 'Cantidad inicial en stock',
            'category' => 'Categoría',
        ],
        'clients' => [
            'add' => 'Agregar nuevo cliente',
            'edit' => 'Editar cliente',
            'created' => 'Cliente creado con éxito',
            'updated' => 'Cliente actualizado con éxito',
            'deleted' => 'Cliente eliminado con éxito',
            'delete_message' => '¿Está seguro de que desea eliminar este cliente?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar los clientes seleccionados?',
            'name' => 'Nombre',
            'email' => 'Correo electrónico',
            'phone' => 'Teléfono',
            'address' => 'Dirección',
        ],
        'orders' => [
            'add' => 'Agregar nuevo pedido',
            'edit' => 'Editar pedido',
            'created' => 'Pedido creado con éxito',
            'updated' => 'Pedido actualizado con éxito',
            'deleted' => 'Pedido eliminado con éxito',
            'delete_message' => '¿Está seguro de que desea eliminar este pedido?',
            'selected_delete_message' => '¿Está seguro de que desea eliminar los pedidos seleccionados?',
            'client_id' => 'Cliente',
            'order_date' => 'Fecha del pedido',
            'total_amount' => 'Cantidad total',
            'user_id' => 'Usuario',
            'order_items' => 'Artículos del pedido',
            'product' => 'Producto',
            'quantity' => 'Cantidad',
            'price' => 'Precio',
            'subtotal' => 'Subtotal',
            'add_order_item' => 'Agregar artículo al pedido',
            'contact_name' => 'Nombre de contacto',
            'contact_phone' => 'Teléfono de contacto',
            'contact_email' => 'Correo electrónico de contacto',
        ],
    ];

    public static $eStoreTranslations = [];

    public static function getTranslationArray($moduleName)
    {
        if ($moduleName == 'Estore') {
            return self::$eStoreTranslations;
        } else if ($moduleName == 'Superadmin') {
            return \App\SuperAdmin\Classes\SuperAdminLangTrans::$mainTranslations;
        }

        return self::$mainTranslations;
    }

    public static function seedTranslations($moduleName = '')
    {
        $allLangs = Lang::all();

        $translations = self::getTranslationArray($moduleName);

        foreach ($translations as $group => $translation) {
            foreach ($translation as $transKey => $transValue) {

                foreach ($allLangs as $allLang) {
                    $translationCount = Translation::where('lang_id', $allLang->id)
                        ->where('group', $group)
                        ->where('key', $transKey)
                        ->count();

                    if ($translationCount == 0) {
                        $newTranslation = new Translation();
                        $newTranslation->lang_id = $allLang->id;
                        $newTranslation->group = $group;
                        $newTranslation->key = $transKey;
                        $newTranslation->value = $transValue;
                        $newTranslation->save();
                    }
                }
            }
        }
    }

    public static function seedMainTranslations()
    {
        // Main Module
        self::seedTranslations();

        // Seeding modules
        self::seedAllModulesTranslations();
    }

    public static function seedAllModulesTranslations()
    {
        $allModules = Module::all();
        foreach ($allModules as $allModule) {
            self::seedTranslations($allModule);
        }
    }
}
